### ISSUE TITLE
Create contributing and issue resources

### ISSUE THREAD

**Issue by kvsun-editor** [KVSun/ad-insertion#57]
**See [Issue and Pull Request templates](https://github.com/blog/2111-issue-and-pull-request-templates)**

Tasks:
- [x] Create `.github/` directory
- [ ] Add `CONTRIBUTING.md` with guidelines from `README.md`.
- [ ] Add `ISSUE_TEMPLATE.md`, asking for screenshots, logs, etc.
- [ ] Add `PULL_REQUEST_TEMPLATE.md`, asking for reference to issue by number.

**Comment by shgysk8zer0** [comment]
I'm trying to figure out how these are presented and otherwise used. For example, does `ISSUE_TEMPATE` appear as `placeholder` when creating a new issue, or does it create actual text in the `textarea`, or does it appear beneath. It seems as though I'll have to just try it and figure this out.

Hopefully, the templates being present in a branch/pull-request will use those templates for creating issues and pull-requests, and `CONTRIBUTING` will appear as it will if merged.
